language: julia
os:
    - linux
julia:
    - '1'
arch:
    - x64
    - arm64
notifications:
    email: false
jobs:
  include:
    - stage: "Documentation"
      julia: '1'
      os: linux
      arch: x64
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
